// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gerrit "github.com/epam/edp-gerrit-operator/v2/pkg/client/gerrit"
	mock "github.com/stretchr/testify/mock"

	platform "github.com/epam/edp-gerrit-operator/v2/pkg/service/platform"

	resty "gopkg.in/resty.v1"

	v1 "github.com/epam/edp-gerrit-operator/v2/pkg/apis/v2/v1"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// AddAccessRights provides a mock function with given fields: projectName, permissions
func (_m *ClientInterface) AddAccessRights(projectName string, permissions []gerrit.AccessInfo) error {
	ret := _m.Called(projectName, permissions)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []gerrit.AccessInfo) error); ok {
		r0 = rf(projectName, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUserToGroup provides a mock function with given fields: groupName, username
func (_m *ClientInterface) AddUserToGroup(groupName string, username string) error {
	ret := _m.Called(groupName, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(groupName, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUserToGroups provides a mock function with given fields: userName, groupNames
func (_m *ClientInterface) AddUserToGroups(userName string, groupNames []string) error {
	ret := _m.Called(userName, groupNames)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(userName, groupNames)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeAbandon provides a mock function with given fields: changeID
func (_m *ClientInterface) ChangeAbandon(changeID string) error {
	ret := _m.Called(changeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(changeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeGet provides a mock function with given fields: changeID
func (_m *ClientInterface) ChangeGet(changeID string) (*gerrit.Change, error) {
	ret := _m.Called(changeID)

	var r0 *gerrit.Change
	if rf, ok := ret.Get(0).(func(string) *gerrit.Change); ok {
		r0 = rf(changeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerrit.Change)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(changeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePassword provides a mock function with given fields: username, password
func (_m *ClientInterface) ChangePassword(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckCredentials provides a mock function with given fields:
func (_m *ClientInterface) CheckCredentials() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckGroup provides a mock function with given fields: groupName
func (_m *ClientInterface) CheckGroup(groupName string) (*int, error) {
	ret := _m.Called(groupName)

	var r0 *int
	if rf, ok := ret.Get(0).(func(string) *int); ok {
		r0 = rf(groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGroup provides a mock function with given fields: name, description, visibleToAll
func (_m *ClientInterface) CreateGroup(name string, description string, visibleToAll bool) (*gerrit.Group, error) {
	ret := _m.Called(name, description, visibleToAll)

	var r0 *gerrit.Group
	if rf, ok := ret.Get(0).(func(string, string, bool) *gerrit.Group); ok {
		r0 = rf(name, description, visibleToAll)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerrit.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(name, description, visibleToAll)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProject provides a mock function with given fields: prj
func (_m *ClientInterface) CreateProject(prj *gerrit.Project) error {
	ret := _m.Called(prj)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gerrit.Project) error); ok {
		r0 = rf(prj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: username, password, fullName, publicKey
func (_m *ClientInterface) CreateUser(username string, password string, fullName string, publicKey string) error {
	ret := _m.Called(username, password, fullName, publicKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(username, password, fullName, publicKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccessRights provides a mock function with given fields: projectName, permissions
func (_m *ClientInterface) DeleteAccessRights(projectName string, permissions []gerrit.AccessInfo) error {
	ret := _m.Called(projectName, permissions)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []gerrit.AccessInfo) error); ok {
		r0 = rf(projectName, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProject provides a mock function with given fields: name
func (_m *ClientInterface) DeleteProject(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserFromGroup provides a mock function with given fields: groupName, username
func (_m *ClientInterface) DeleteUserFromGroup(groupName string, username string) error {
	ret := _m.Called(groupName, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(groupName, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProject provides a mock function with given fields: name
func (_m *ClientInterface) GetProject(name string) (*gerrit.Project, error) {
	ret := _m.Called(name)

	var r0 *gerrit.Project
	if rf, ok := ret.Get(0).(func(string) *gerrit.Project); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerrit.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitAdminUser provides a mock function with given fields: instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey
func (_m *ClientInterface) InitAdminUser(instance *v1.Gerrit, _a1 platform.PlatformService, GerritScriptsPath string, podName string, gerritAdminPublicKey string) (*v1.Gerrit, error) {
	ret := _m.Called(instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey)

	var r0 *v1.Gerrit
	if rf, ok := ret.Get(0).(func(*v1.Gerrit, platform.PlatformService, string, string, string) *v1.Gerrit); ok {
		r0 = rf(instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Gerrit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Gerrit, platform.PlatformService, string, string, string) error); ok {
		r1 = rf(instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitAllProjects provides a mock function with given fields: instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey
func (_m *ClientInterface) InitAllProjects(instance *v1.Gerrit, _a1 platform.PlatformService, GerritScriptsPath string, podName string, gerritAdminPublicKey string) error {
	ret := _m.Called(instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Gerrit, platform.PlatformService, string, string, string) error); ok {
		r0 = rf(instance, _a1, GerritScriptsPath, podName, gerritAdminPublicKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitNewRestClient provides a mock function with given fields: instance, url, user, password
func (_m *ClientInterface) InitNewRestClient(instance *v1.Gerrit, url string, user string, password string) error {
	ret := _m.Called(instance, url, user, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Gerrit, string, string, string) error); ok {
		r0 = rf(instance, url, user, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitNewSshClient provides a mock function with given fields: userName, privateKey, host, port
func (_m *ClientInterface) InitNewSshClient(userName string, privateKey []byte, host string, port int32) error {
	ret := _m.Called(userName, privateKey, host, port)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, string, int32) error); ok {
		r0 = rf(userName, privateKey, host, port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProjectBranches provides a mock function with given fields: projectName
func (_m *ClientInterface) ListProjectBranches(projectName string) ([]gerrit.Branch, error) {
	ret := _m.Called(projectName)

	var r0 []gerrit.Branch
	if rf, ok := ret.Get(0).(func(string) []gerrit.Branch); ok {
		r0 = rf(projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gerrit.Branch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProjects provides a mock function with given fields: _type
func (_m *ClientInterface) ListProjects(_type string) ([]gerrit.Project, error) {
	ret := _m.Called(_type)

	var r0 []gerrit.Project
	if rf, ok := ret.Get(0).(func(string) []gerrit.Project); ok {
		r0 = rf(_type)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gerrit.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_type)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReloadPlugin provides a mock function with given fields: plugin
func (_m *ClientInterface) ReloadPlugin(plugin string) error {
	ret := _m.Called(plugin)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(plugin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Resty provides a mock function with given fields:
func (_m *ClientInterface) Resty() *resty.Client {
	ret := _m.Called()

	var r0 *resty.Client
	if rf, ok := ret.Get(0).(func() *resty.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resty.Client)
		}
	}

	return r0
}

// SetProjectParent provides a mock function with given fields: projectName, parentName
func (_m *ClientInterface) SetProjectParent(projectName string, parentName string) error {
	ret := _m.Called(projectName, parentName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(projectName, parentName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAccessRights provides a mock function with given fields: projectName, permissions
func (_m *ClientInterface) UpdateAccessRights(projectName string, permissions []gerrit.AccessInfo) error {
	ret := _m.Called(projectName, permissions)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []gerrit.AccessInfo) error); ok {
		r0 = rf(projectName, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroup provides a mock function with given fields: groupID, description, visibleToAll
func (_m *ClientInterface) UpdateGroup(groupID string, description string, visibleToAll bool) error {
	ret := _m.Called(groupID, description, visibleToAll)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(groupID, description, visibleToAll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProject provides a mock function with given fields: prj
func (_m *ClientInterface) UpdateProject(prj *gerrit.Project) error {
	ret := _m.Called(prj)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gerrit.Project) error); ok {
		r0 = rf(prj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClientInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientInterface(t mockConstructorTestingTNewClientInterface) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
