// Code generated by mockery v2.16.0. DO NOT EDIT.

package mock

import (
	context "context"
	"github.com/epam/edp-gerrit-operator/v2/api/v1"

	clientgerrit "github.com/epam/edp-gerrit-operator/v2/pkg/client/gerrit"

	gerrit "github.com/epam/edp-gerrit-operator/v2/pkg/service/gerrit"

	git "github.com/epam/edp-gerrit-operator/v2/pkg/client/git"

	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Configure provides a mock function with given fields: instance
func (_m *Interface) Configure(instance *v1.Gerrit) (*v1.Gerrit, bool, error) {
	ret := _m.Called(instance)

	var r0 *v1.Gerrit
	if rf, ok := ret.Get(0).(func(*v1.Gerrit) *v1.Gerrit); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Gerrit)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*v1.Gerrit) bool); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*v1.Gerrit) error); ok {
		r2 = rf(instance)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExposeConfiguration provides a mock function with given fields: ctx, instance
func (_m *Interface) ExposeConfiguration(ctx context.Context, instance *v1.Gerrit) (*v1.Gerrit, error) {
	ret := _m.Called(ctx, instance)

	var r0 *v1.Gerrit
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Gerrit) *v1.Gerrit); ok {
		r0 = rf(ctx, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Gerrit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.Gerrit) error); ok {
		r1 = rf(ctx, instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGerritSSHUrl provides a mock function with given fields: instance
func (_m *Interface) GetGerritSSHUrl(instance *v1.Gerrit) (string, error) {
	ret := _m.Called(instance)

	var r0 string
	if rf, ok := ret.Get(0).(func(*v1.Gerrit) string); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGitClient provides a mock function with given fields: ctx, child, workDir
func (_m *Interface) GetGitClient(ctx context.Context, child gerrit.Child, workDir string) (*git.Client, error) {
	ret := _m.Called(ctx, child, workDir)

	var r0 *git.Client
	if rf, ok := ret.Get(0).(func(context.Context, gerrit.Child, string) *git.Client); ok {
		r0 = rf(ctx, child, workDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gerrit.Child, string) error); ok {
		r1 = rf(ctx, child, workDir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestClient provides a mock function with given fields: gerritInstance
func (_m *Interface) GetRestClient(gerritInstance *v1.Gerrit) (clientgerrit.ClientInterface, error) {
	ret := _m.Called(gerritInstance)

	var r0 clientgerrit.ClientInterface
	if rf, ok := ret.Get(0).(func(*v1.Gerrit) clientgerrit.ClientInterface); ok {
		r0 = rf(gerritInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientgerrit.ClientInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Gerrit) error); ok {
		r1 = rf(gerritInstance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServicePort provides a mock function with given fields: instance
func (_m *Interface) GetServicePort(instance *v1.Gerrit) (int32, error) {
	ret := _m.Called(instance)

	var r0 int32
	if rf, ok := ret.Get(0).(func(*v1.Gerrit) int32); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Integrate provides a mock function with given fields: ctx, instance
func (_m *Interface) Integrate(ctx context.Context, instance *v1.Gerrit) (*v1.Gerrit, error) {
	ret := _m.Called(ctx, instance)

	var r0 *v1.Gerrit
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Gerrit) *v1.Gerrit); ok {
		r0 = rf(ctx, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Gerrit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.Gerrit) error); ok {
		r1 = rf(ctx, instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsDeploymentReady provides a mock function with given fields: instance
func (_m *Interface) IsDeploymentReady(instance *v1.Gerrit) (bool, error) {
	ret := _m.Called(instance)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1.Gerrit) bool); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInterface(t mockConstructorTestingTNewInterface) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
