// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/stretchr/testify/mock"

	gerritApi "github.com/epam/edp-gerrit-operator/v2/pkg/apis/v2/v1"
	clientgerrit "github.com/epam/edp-gerrit-operator/v2/pkg/client/gerrit"
	git "github.com/epam/edp-gerrit-operator/v2/pkg/client/git"
	gerrit "github.com/epam/edp-gerrit-operator/v2/pkg/service/gerrit"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Configure provides a mock function with given fields: instance
func (_m *Interface) Configure(instance *gerritApi.Gerrit) (*gerritApi.Gerrit, bool, error) {
	ret := _m.Called(instance)

	var r0 *gerritApi.Gerrit
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) *gerritApi.Gerrit); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerritApi.Gerrit)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) bool); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*gerritApi.Gerrit) error); ok {
		r2 = rf(instance)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExposeConfiguration provides a mock function with given fields: instance
func (_m *Interface) ExposeConfiguration(instance *gerritApi.Gerrit) (*gerritApi.Gerrit, error) {
	ret := _m.Called(instance)

	var r0 *gerritApi.Gerrit
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) *gerritApi.Gerrit); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerritApi.Gerrit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGerritSSHUrl provides a mock function with given fields: instance
func (_m *Interface) GetGerritSSHUrl(instance *gerritApi.Gerrit) (string, error) {
	ret := _m.Called(instance)

	var r0 string
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) string); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGitClient provides a mock function with given fields: ctx, child, workDir
func (_m *Interface) GetGitClient(ctx context.Context, child gerrit.Child, workDir string) (*git.Client, error) {
	ret := _m.Called(ctx, child, workDir)

	var r0 *git.Client
	if rf, ok := ret.Get(0).(func(context.Context, gerrit.Child, string) *git.Client); ok {
		r0 = rf(ctx, child, workDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gerrit.Child, string) error); ok {
		r1 = rf(ctx, child, workDir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestClient provides a mock function with given fields: gerritInstance
func (_m *Interface) GetRestClient(gerritInstance *gerritApi.Gerrit) (clientgerrit.ClientInterface, error) {
	ret := _m.Called(gerritInstance)

	var r0 clientgerrit.ClientInterface
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) clientgerrit.ClientInterface); ok {
		r0 = rf(gerritInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientgerrit.ClientInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(gerritInstance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServicePort provides a mock function with given fields: instance
func (_m *Interface) GetServicePort(instance *gerritApi.Gerrit) (int32, error) {
	ret := _m.Called(instance)

	var r0 int32
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) int32); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Integrate provides a mock function with given fields: instance
func (_m *Interface) Integrate(instance *gerritApi.Gerrit) (*gerritApi.Gerrit, error) {
	ret := _m.Called(instance)

	var r0 *gerritApi.Gerrit
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) *gerritApi.Gerrit); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gerritApi.Gerrit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsDeploymentReady provides a mock function with given fields: instance
func (_m *Interface) IsDeploymentReady(instance *gerritApi.Gerrit) (bool, error) {
	ret := _m.Called(instance)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*gerritApi.Gerrit) bool); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gerritApi.Gerrit) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
