apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gerritmergerequests.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: GerritMergeRequest
    listKind: GerritMergeRequestList
    plural: gerritmergerequests
    singular: gerritmergerequest
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                ownerName:
                  type: string
                  nullable: true
                  description: 'Property indicates which gerrit car should be taken to initialize correct client.'
                projectName:
                  type: string
                  description: 'gerrit project name'
                sourceBranch:
                  type: string
                targetBranch:
                  type: string
                  description: 'optional, default is master'
                commitMessage:
                  type: string
                  description: 'merge commit message'
                authorName:
                  type: string
                authorEmail:
                  type: string
                changesConfigMap:
                  type: string
                additionalArguments:
                  nullable: true
                  type: array
                  description: 'merge command additional command line arguments'
                  items:
                    type: string
              required:
                - ownerName
                - projectName
                - authorName
                - authorEmail
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}