apiVersion: v2
description: A Helm chart for KubeRocketCI Gerrit Operator
home: https://docs.kuberocketci.io/
name: gerrit-operator
type: application
version: 2.24.0-SNAPSHOT
appVersion: 2.24.0-SNAPSHOT
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - edp
  - gerrit
  - operator
  - git
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-gerrit-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: gerrit-operator:2.23.1
      image: epamedp/gerrit-operator:2.23.1
    - name: edp-gerrit:3.6.2-oauth
      image: epamedp/edp-gerrit:3.6.2-oauth
    - name: alpine:3.18.9
      image: alpine:3.18.9
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: Gerrit
      version: v2.edp.epam.com/v1
      name: gerrit
      displayName: Gerrit
      description: Operates Gerrit application
    - kind: GerritGroup
      version: v2.edp.epam.com/v1
      name: gerritgroup
      displayName: GerritGroup
      description: Operates Gerrit groups
    - kind: GerritGroupMember
      version: v2.edp.epam.com/v1
      name: gerritgroupmember
      displayName: GerritGroupMember
      description: Operates Gerrit group member access
    - kind: GerritProject
      version: v2.edp.epam.com/v1
      name: gerritproject
      displayName: GerritProject
      description: Creates repo on a Gerrit server
    - kind: GerritProjectAccess
      version: v2.edp.epam.com/v1
      name: gerritprojectaccess
      displayName: GerritProjectAccess
      description: Operates Gerrit group accesses
    - kind: GerritReplicationConfig
      version: v2.edp.epam.com/v1
      name: gerritreplicationconfig
      displayName: GerritReplicationConfig
      description: Takes part in replication
    - kind: GerritMergeRequest
      version: v2.edp.epam.com/v1
      name: gerritmergerequest
      displayName: GerritMergeRequest
      description: Takes part in merge requests
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1
      kind: Gerrit
      metadata:
        name: gerrit
      spec:
        keycloakSpec:
          enabled: true
        sshPort: 30024
    - apiVersion: v2.edp.epam.com/v1
      kind: GerritGroup
      metadata:
        name: developers
      spec:
        description: Gerrit Site Developers
        gerritOwner: 'test'
        name: Developers
        visibleToAll: false
    - apiVersion: v2.edp.epam.com/v1
      kind: GerritGroupMember
      metadata:
        name: reader
      spec:
        accountId: reader
        groupId: Developers
        ownerName: 'test'
    - apiVersion: v2.edp.epam.com/v1
      kind: GerritProject
      metadata:
        name: gerrit-test
      spec:
        branches: 'master'
        createEmptyCommit: false
        description: 'test'
        name: gerrit-test
        ownerName: gerrit
        owners: 'test'
        parent: All-Projects
        permissionsOnly: false
        rejectEmptyCommit: 'test'
        submitType: 'test'
    - apiVersion: v2.edp.epam.com/v1
      kind: GerritMergeRequest
      metadata:
        name: gerritmergerequest
      spec:
        ownerName: gerrit
        targetBranch: master
        sourceBranch: rev123
        projectName: testmerge1
        commitMessage: kawabunga
        authorName: John Doe
        authorEmail: john.doe@example.com
        changesConfigMap: demo-changes
        additionalArguments: null
    - apiVersion: v2.edp.epam.com/v1
      kind: GerritProjectAccess
      metadata:
        name: test-access1
      spec:
        projectName: test123
        references:
          - refPattern: "refs/for/*"
            permissionName: "label-Verified"
            groupName: "Administrators"
            action: "ALLOW"
            min: -1
            max: 1
          - refPattern: "refs/for/*"
            permissionName: "label-Verified"
            groupName: "test321"
            action: "ALLOW"
            min: -1
            max: 1
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
