apiVersion: v2
description: Helm chart for Golang application/service deploying
name: gerrit-operator
keywords:
    - Golang
home: https://solutionshub.epam.com/solution/epam-delivery-platform
type: application
maintainers:
    - name: EPAM EDP Team
sources:
    - https://github.com/epam/edp-gerrit-operator
appVersion: 2.5.0-SNAPSHOT
version: 2.5.0-SNAPSHOT
