apiVersion: v2
description: A Helm chart for EDP Gerrit Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: gerrit-operator
type: application
version: 2.7.0
appVersion: v2.7.0
maintainers:
    - name: EPAM EDP Team
sources:
    - https://github.com/epam/edp-gerrit-operator
