{{- if .Values.gerrit.deploy -}}
apiVersion: v2.edp.epam.com/v1
kind: Gerrit
metadata:
  name: {{.Values.gerrit.name}}
spec:
  keycloakSpec:
    # SSO enabled is deprecated and we configure Keycloak via Helm chart
    enabled: false
  sshPort: {{ .Values.global.gerritSSHPort }}
{{end}}
