{{- if .Values.gerrit.deploy -}}
apiVersion: v2.edp.epam.com/v1
kind: Gerrit
metadata:
  name: {{.Values.gerrit.name}}
spec:
  keycloakSpec:
    enabled: true
  sshPort: {{ .Values.global.gerritSSHPort }}
{{end}}
