{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-{{ .Values.global.edpName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edp-{{ .Values.name }}-role-{{ .Values.global.edpName }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.name }}-edp"
    namespace: {{ .Values.global.edpName }}
{{ end }}