{{- if .Values.gerrit.deploy -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.gerrit.name}}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: {{.Values.gerrit.name}}
spec:
  ports:
    - name: ui
      port: {{.Values.gerrit.port}}
      protocol: TCP
      targetPort: {{.Values.gerrit.port}}
    - name: ssh
      nodePort: {{ .Values.global.gerritSSHPort }}
      port: {{ .Values.global.gerritSSHPort }}
      protocol: TCP
      targetPort: {{ .Values.global.gerritSSHPort }}
  selector:
    app: {{.Values.gerrit.name}}
  sessionAffinity: None
  type: NodePort
{{- end -}}