{{- if .Values.gerrit.deploy -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.gerrit.name}}
  labels:
    app: {{.Values.gerrit.name}}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
{{- end -}}