{{ if eq .Values.global.platform "kubernetes" }}
{{- $ingressApiIsStable := eq (include "gerrit.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "gerrit.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "gerrit.ingress.supportsPathType" .) "true" -}}
{{- $ingressPathType := .Values.gerrit.ingress.pathType -}}
kind: Ingress
apiVersion: {{ include "gerrit.ingress.apiVersion" . }}
metadata:
  name: {{ .Values.gerrit.name }}
  labels:
    app: {{ .Values.gerrit.name }}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  {{- with .Values.gerrit.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.gerrit.ingress.ingressClassName }}
  ingressClassName: {{ .Values.gerrit.ingress.ingressClassName }}
  {{- end }}
{{- if .Values.gerrit.ingress.tls }}
  tls:
    {{- range .Values.gerrit.ingress.tls }}
    - hosts:
        {{- if .hosts }}
        {{- toYaml .hosts | nindent 8 }}
        {{- else }}
        - {{ include "gerrit.url" $ }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.gerrit.ingress.host }}
    - host: {{ .Values.gerrit.ingress.host }}
    {{- else}}
    - host: {{ include "gerrit.url" . }}
    {{- end}}
      http:
        paths:
          - path: {{if .Values.gerrit.basePath}}/{{.Values.gerrit.basePath}}(/|$)(.*){{else}}/{{end}}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ .Values.gerrit.name }}
                port:
                  number: 8080
              {{- else }}
              serviceName: {{ .Values.gerrit.name }}
              servicePort: 8080
              {{- end }}
{{ end }}
