{{ if eq .Values.global.platform "kubernetes" }}
{{- $ingressApiIsStable := eq (include "gerrit.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "gerrit.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "gerrit.ingress.supportsPathType" .) "true" -}}
{{- $ingressPathType := .Values.gerrit.ingress.pathType -}}
kind: Ingress
apiVersion: {{ include "gerrit.ingress.apiVersion" . }}
metadata:
  name: {{ .Values.gerrit.name }}
  labels:
    app: {{ .Values.gerrit.name }}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  {{- with .Values.gerrit.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.gerrit.ingress.ingressClassName }}
  ingressClassName: {{ .Values.gerrit.ingress.ingressClassName }}
  {{- end }}
{{- if .Values.gerrit.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.gerrit.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
    - host: {{if .Values.gerrit.basePath}}{{ .Values.global.dnsWildCard }}{{else}}gerrit-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}{{end}}
      http:
        paths:
          - path: {{if .Values.gerrit.basePath}}/{{.Values.gerrit.basePath}}(/|$)(.*){{else}}/{{end}}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ .Values.gerrit.name }}
                port: 
                  number: 8080
              {{- else }}
              serviceName: {{ .Values.gerrit.name }}
              servicePort: 8080
              {{- end }}
{{ end }}
