{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
    - 'rbac.authorization.k8s.io'
  resources:
    - podsecuritypolicies
  verbs:
    - update
    - get
    - list
- apiGroups:
    - '*'
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
  verbs:
    - '*'
- apiGroups:
    - '*'
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - jenkinsserviceaccounts
    - jenkinsscripts
    - edpcomponents
  verbs:
    - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{ end }}
