{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubernetes.io/description: Role for {{ .Values.name }}-edp service account
    kubernetes.io/reconcile-protect: "false"
  name: edp-{{ .Values.name }}-role-{{ .Values.global.edpName }}
rules:
- apiGroups:
    - 'rbac.authorization.k8s.io'
  attributeRestrictions: null
  resources:
    - podsecuritypolicies
  verbs:
    - update
    - get
    - list
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
  verbs:
    - '*'
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - jenkinsserviceaccounts
    - jenkinsscripts
    - edpcomponents
  verbs:
    - '*'
{{ end }}
