{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
roleRef:
  name: edp-{{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: edp-gerrit-operator
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount:{{ .Values.global.edpName }}:edp-gerrit-operator
groupNames: []
{{- end -}}
