{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
roleRef:
  name: edp-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: edp-gerrit-operator
    namespace: {{ .Release.Namespace }}
userNames:
  - system:serviceaccount:{{ .Release.Namespace }}:edp-gerrit-operator
{{- end -}}
