{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
    - '*'
  resources:
    - securitycontextconstraints
  verbs:
    - patch
    - update
    - delete
    - get
    - list
    - create
- apiGroups:
    - '*'
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
  verbs:
    - '*'
- apiGroups:
    - '*'
  resources:
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
    - keycloaks
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/status
    - jenkinsserviceaccounts
    - jenkinsscripts
    - edpcomponents
  verbs:
    - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{ end }}
