{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: gerrit-operator-{{ .Values.global.edpName }}
roleRef:
  name: gerrit-operator-role-{{ .Values.global.edpName }}
subjects:
  - kind: ServiceAccount
    name: gerrit-operator-edp
    namespace: {{ .Values.global.edpName }}
userNames:
  - system:serviceaccount:{{ .Values.global.edpName }}:gerrit-operator-edp
groupNames: []
{{- end -}}