{{if eq .Values.global.platform "kubernetes"}}
{{if .Values.gerrit.deploy}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-{{.Values.gerrit.name}}-{{.Values.global.edpName}}-clusterrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{.Values.gerrit.name}}-{{.Values.global.edpName}}
  verbs:
  - use
{{end}}
{{end}}