{{if eq .Values.global.platform "kubernetes"}}
{{if .Values.gerrit.deploy}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-{{.Values.gerrit.name}}-{{.Values.global.edpName}}
roleRef:
  kind: ClusterRole
  name: psp-{{.Values.gerrit.name}}-{{.Values.global.edpName}}-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{.Values.gerrit.name}}
  namespace: {{ .Values.global.edpName }}
{{end}}
{{end}}