{{- if eq .Values.global.platform "openshift" -}}
{{- if .Values.gerrit.deploy -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.gerrit.name}}
  labels:
    app: {{.Values.gerrit.name}}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  {{- with .Values.gerrit.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
    host: {{if .Values.gerrit.basePath}}{{.Values.global.dnsWildCard}}{{else}}gerrit-{{ .Release.Namespace }}.{{.Values.global.dnsWildCard}}{{end}}
    path: {{if .Values.gerrit.basePath}}/{{.Values.gerrit.basePath}}(/|$)(.*){{else}}/{{end}}
    port:
        targetPort: {{.Values.gerrit.port}}
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
    to:
        kind: Service
        name: {{.Values.gerrit.name}}
        weight: 100
    wildcardPolicy: None
status:
    ingress: []
{{- end -}}
{{- end -}}