{{- if .Values.gerrit.deploy -}}
apiVersion: v1
data:
  sshPort: "{{ .Values.global.gerritSSHPort }}"
kind: ConfigMap
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: {{.Values.gerrit.name}}
{{end}}
