// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"gerrit-operator/pkg/apis/edp/v1alpha1.Gerrit":       schema_pkg_apis_edp_v1alpha1_Gerrit(ref),
		"gerrit-operator/pkg/apis/edp/v1alpha1.GerritSpec":   schema_pkg_apis_edp_v1alpha1_GerritSpec(ref),
		"gerrit-operator/pkg/apis/edp/v1alpha1.GerritStatus": schema_pkg_apis_edp_v1alpha1_GerritStatus(ref),
	}
}

func schema_pkg_apis_edp_v1alpha1_Gerrit(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Gerrit is the Schema for the gerrits API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gerrit-operator/pkg/apis/edp/v1alpha1.GerritSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("gerrit-operator/pkg/apis/edp/v1alpha1.GerritStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"gerrit-operator/pkg/apis/edp/v1alpha1.GerritSpec", "gerrit-operator/pkg/apis/edp/v1alpha1.GerritStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_edp_v1alpha1_GerritSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GerritSpec defines the desired state of Gerrit",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_edp_v1alpha1_GerritStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GerritStatus defines the observed state of Gerrit",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
